services:
  - type: web
    name: upway-app
    env: node
    plan: free
    buildCommand: npm install --include=dev && npx prisma db push --accept-data-loss && NODE_OPTIONS=--max_old_space_size=450 npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NPM_CONFIG_PRODUCTION
        value: false
      - key: NODE_OPTIONS
        value: --max_old_space_size=450
      - key: META_VERIFY_TOKEN
        sync: false
      - key: WHATSAPP_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GEMINI_PREMIUM_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: KIMI_API_KEY
        sync: false
      - key: KIMI_API_URL
        sync: false
      - key: KIMI_MODEL
        sync: false
      - key: SAMBANOVA_API_KEY
        sync: false
      - key: MISTRAL_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: CEREBRAS_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
