services:
  - type: web
    name: upway-app
    env: node
    plan: free
    buildCommand: npm install && npm run build
    preDeployCommand: npx prisma db push
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
