services:
  - type: web
    name: upway-app
    env: node
    plan: free
    buildCommand: npm install --include=dev && npx prisma db push --accept-data-loss && NODE_OPTIONS=--max_old_space_size=450 npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NPM_CONFIG_PRODUCTION
        value: false
      - key: NODE_OPTIONS
        value: --max_old_space_size=450
